// examples/framework-react/App.tsx
/**
 * Heroine Graph React Example
 *
 * Demonstrates the @graphmother/react wrapper with:
 * - Basic graph rendering
 * - Event handling
 * - Simulation controls
 */

import { useCallback, useRef, useState } from "react";
import { HeroineGraph } from "@graphmother/react";
import type { EdgeInput, GraphInput, HeroineGraphRef, NodeClickEvent } from "@graphmother/react";

// Generate sample graph data
function generateGraph(nodeCount: number): GraphInput {
  const nodes = Array.from({ length: nodeCount }, (_, i) => ({
    id: i,
    label: `Node ${i}`,
    type: i % 3 === 0 ? "primary" : i % 3 === 1 ? "secondary" : "tertiary",
  }));

  // GraphInput["edges"] is readonly; build with a mutable array
  const edges: EdgeInput[] = [];
  for (let i = 1; i < nodeCount; i++) {
    // Create a tree structure with some cross-links
    edges.push({ source: Math.floor(i / 2), target: i });

    // Add random cross-links
    if (Math.random() > 0.7 && i > 3) {
      edges.push({ source: Math.floor(Math.random() * i), target: i });
    }
  }

  return { nodes, edges };
}

function App() {
  const graphRef = useRef<HeroineGraphRef>(null);
  const [graphData] = useState(() => generateGraph(100));
  const [selectedNode, setSelectedNode] = useState<number | null>(null);
  const [eventLog, setEventLog] = useState<string[]>([]);

  const addLog = useCallback((message: string) => {
    setEventLog((prev) => [message, ...prev.slice(0, 9)]);
  }, []);

  const handleNodeClick = useCallback((event: NodeClickEvent) => {
    setSelectedNode(event.nodeId as number);
    addLog(`Clicked node ${event.nodeId}`);
  }, [addLog]);

  const handleReady = useCallback(() => {
    addLog("Graph ready!");
  }, [addLog]);

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%" }}>
      {/* Header */}
      <header
        style={{
          padding: "16px 24px",
          borderBottom: "1px solid #333",
          display: "flex",
          alignItems: "center",
          gap: "24px",
        }}
      >
        <h1 style={{ fontSize: "1.25rem", fontWeight: 600 }}>
          Heroine Graph - React
        </h1>
        {selectedNode !== null && (
          <span style={{ color: "#888" }}>
            Selected: Node {selectedNode}
          </span>
        )}
      </header>

      {/* Main Content */}
      <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>
        {/* Graph */}
        <main style={{ flex: 1, position: "relative" }}>
          <HeroineGraph
            ref={graphRef}
            data={graphData}
            onReady={handleReady}
            onNodeClick={handleNodeClick}
            onNodeHoverEnter={(e) => addLog(`Hover enter: ${e.nodeId}`)}
            onNodeHoverLeave={(e) => addLog(`Hover leave: ${e.nodeId}`)}
            onSimulationEnd={() => addLog("Simulation ended")}
            style={{ width: "100%", height: "100%" }}
          />
        </main>

        {/* Sidebar */}
        <aside
          style={{
            width: "280px",
            borderLeft: "1px solid #333",
            padding: "16px",
            display: "flex",
            flexDirection: "column",
            gap: "16px",
            overflow: "auto",
          }}
        >
          {/* Controls */}
          <section>
            <h2
              style={{
                fontSize: "0.875rem",
                fontWeight: 600,
                marginBottom: "12px",
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                color: "#888",
              }}
            >
              Controls
            </h2>
            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
              <button
                type="button"
                onClick={() => graphRef.current?.getGraph()?.fitToView()}
                style={buttonStyle}
              >
                Fit to View
              </button>
              <button
                type="button"
                onClick={() => graphRef.current?.getGraph()?.restartSimulation()}
                style={buttonStyle}
              >
                Restart Simulation
              </button>
              <button
                type="button"
                onClick={() => graphRef.current?.getGraph()?.clearSelection()}
                style={buttonStyle}
              >
                Clear Selection
              </button>
            </div>
          </section>

          {/* Event Log */}
          <section style={{ flex: 1, minHeight: 0 }}>
            <h2
              style={{
                fontSize: "0.875rem",
                fontWeight: 600,
                marginBottom: "12px",
                textTransform: "uppercase",
                letterSpacing: "0.05em",
                color: "#888",
              }}
            >
              Event Log
            </h2>
            <div
              style={{
                background: "#111",
                borderRadius: "6px",
                padding: "12px",
                height: "200px",
                overflow: "auto",
                fontSize: "0.75rem",
                fontFamily: "monospace",
              }}
            >
              {eventLog.length === 0 ? <span style={{ color: "#666" }}>No events yet...</span> : (
                eventLog.map((log, i) => (
                  <div key={i} style={{ color: "#aaa", marginBottom: "4px" }}>
                    {log}
                  </div>
                ))
              )}
            </div>
          </section>
        </aside>
      </div>
    </div>
  );
}

const buttonStyle: React.CSSProperties = {
  padding: "8px 12px",
  background: "#222",
  border: "1px solid #444",
  borderRadius: "4px",
  color: "#fff",
  cursor: "pointer",
  fontSize: "0.875rem",
};

export default App;

// examples/framework-svelte/App.svelte
<!--
  Heroine Graph Svelte Example

  Demonstrates the @graphmother/svelte wrapper with:
  - Basic graph rendering
  - Event handling
  - Simulation controls
-->
<script lang="ts">
    import { HeroineGraph } from "@graphmother/svelte";
    import type {
        EdgeInput,
        GraphInput,
        NodeClickEvent,
        NodeHoverEnterEvent,
        NodeHoverLeaveEvent,
    } from "@graphmother/svelte";
    import type { HeroineGraph as HeroineGraphCore } from "@graphmother/core";

    // State
    let graphComponent = $state<{
        getGraph: () => HeroineGraphCore | null;
    } | null>(null);
    let selectedNode = $state<number | null>(null);
    let eventLog = $state<string[]>([]);

    // Generate sample graph data
    function generateGraph(nodeCount: number): GraphInput {
        const nodes = Array.from({ length: nodeCount }, (_, i) => ({
            id: i,
            label: `Node ${i}`,
            type:
                i % 3 === 0
                    ? "primary"
                    : i % 3 === 1
                      ? "secondary"
                      : "tertiary",
        }));

        // GraphInput["edges"] is readonly; build with a mutable array
        const edges: EdgeInput[] = [];
        for (let i = 1; i < nodeCount; i++) {
            edges.push({ source: Math.floor(i / 2), target: i });
            if (Math.random() > 0.7 && i > 3) {
                edges.push({
                    source: Math.floor(Math.random() * i),
                    target: i,
                });
            }
        }

        return { nodes, edges };
    }

    const graphData = generateGraph(100);

    // Event handlers
    function addLog(message: string) {
        eventLog = [message, ...eventLog.slice(0, 9)];
    }

    function onReady(_graph: HeroineGraphCore) {
        addLog("Graph ready!");
    }

    function onNodeClick(event: NodeClickEvent) {
        selectedNode = event.nodeId as number;
        addLog(`Clicked node ${event.nodeId}`);
    }

    function onNodeHoverEnter(event: NodeHoverEnterEvent) {
        addLog(`Hover enter: ${event.nodeId}`);
    }

    function onNodeHoverLeave(event: NodeHoverLeaveEvent) {
        addLog(`Hover leave: ${event.nodeId}`);
    }

    function onSimulationEnd() {
        addLog("Simulation ended");
    }

    // Control methods
    function fitToView() {
        graphComponent?.getGraph()?.fitToView();
    }

    function restartSimulation() {
        graphComponent?.getGraph()?.restartSimulation();
    }

    function clearSelection() {
        graphComponent?.getGraph()?.clearSelection();
        selectedNode = null;
    }
</script>

<div class="app">
    <!-- Header -->
    <header class="header">
        <h1>Heroine Graph - Svelte</h1>
        {#if selectedNode !== null}
            <span class="selected">Selected: Node {selectedNode}</span>
        {/if}
    </header>

    <!-- Main Content -->
    <div class="content">
        <!-- Graph -->
        <main class="graph-container">
            <HeroineGraph
                bind:this={graphComponent}
                data={graphData}
                onready={onReady}
                onnodeClick={onNodeClick}
                onnodeHoverEnter={onNodeHoverEnter}
                onnodeHoverLeave={onNodeHoverLeave}
                onsimulationEnd={onSimulationEnd}
                width="100%"
                height="100%"
            />
        </main>

        <!-- Sidebar -->
        <aside class="sidebar">
            <!-- Controls -->
            <section class="section">
                <h2 class="section-title">Controls</h2>
                <div class="button-group">
                    <button class="btn" onclick={fitToView}>Fit to View</button>
                    <button class="btn" onclick={restartSimulation}
                        >Restart Simulation</button
                    >
                    <button class="btn" onclick={clearSelection}
                        >Clear Selection</button
                    >
                </div>
            </section>

            <!-- Event Log -->
            <section class="section log-section">
                <h2 class="section-title">Event Log</h2>
                <div class="event-log">
                    {#if eventLog.length === 0}
                        <span class="no-events">No events yet...</span>
                    {:else}
                        {#each eventLog as log, i}
                            <div class="log-entry">{log}</div>
                        {/each}
                    {/if}
                </div>
            </section>
        </aside>
    </div>
</div>

<style>
    .app {
        display: flex;
        flex-direction: column;
        height: 100%;
    }

    .header {
        padding: 16px 24px;
        border-bottom: 1px solid #333;
        display: flex;
        align-items: center;
        gap: 24px;
    }

    .header h1 {
        font-size: 1.25rem;
        font-weight: 600;
    }

    .selected {
        color: #888;
    }

    .content {
        display: flex;
        flex: 1;
        overflow: hidden;
    }

    .graph-container {
        flex: 1;
        position: relative;
    }

    .sidebar {
        width: 280px;
        border-left: 1px solid #333;
        padding: 16px;
        display: flex;
        flex-direction: column;
        gap: 16px;
        overflow: auto;
    }

    .section-title {
        font-size: 0.875rem;
        font-weight: 600;
        margin-bottom: 12px;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        color: #888;
    }

    .button-group {
        display: flex;
        flex-direction: column;
        gap: 8px;
    }

    .btn {
        padding: 8px 12px;
        background: #222;
        border: 1px solid #444;
        border-radius: 4px;
        color: #fff;
        cursor: pointer;
        font-size: 0.875rem;
    }

    .btn:hover {
        background: #333;
    }

    .log-section {
        flex: 1;
        min-height: 0;
    }

    .event-log {
        background: #111;
        border-radius: 6px;
        padding: 12px;
        height: 200px;
        overflow: auto;
        font-size: 0.75rem;
        font-family: monospace;
    }

    .no-events {
        color: #666;
    }

    .log-entry {
        color: #aaa;
        margin-bottom: 4px;
    }
</style>
