// packages/vue/src/HeroineGraph.vue
<!--
  HeroineGraph Vue Component

  A Vue wrapper for the Heroine Graph visualization library.
  Handles WebGPU initialization, lifecycle management, and event forwarding.

  @module
-->
<template>
  <div
    ref="containerRef"
    :class="className"
    :style="containerStyle"
  >
    <div
      v-if="error"
      :style="errorStyle"
    >
      <div style="font-size: 1.2em; margin-bottom: 8px;">
        Failed to initialize graph
      </div>
      <div style="opacity: 0.8; font-size: 0.9em;">{{ error.message }}</div>
    </div>
    <canvas
      v-else
      ref="canvasRef"
      style="width: 100%; height: 100%; display: block;"
    />
  </div>
</template>

<script setup lang="ts">
import {
  ref,
  computed,
  watch,
  onMounted,
  onUnmounted,
  type CSSProperties,
} from "vue";
import type {
  GraphConfig,
  GraphInput,
  HeroineGraph as HeroineGraphCore,
  NodeClickEvent,
  NodeDoubleClickEvent,
  NodeDragEndEvent,
  NodeDragMoveEvent,
  NodeDragStartEvent,
  NodeHoverEnterEvent,
  NodeHoverLeaveEvent,
  EdgeClickEvent,
  EdgeHoverEnterEvent,
  EdgeHoverLeaveEvent,
  SelectionChangeEvent,
  ViewportChangeEvent,
  SimulationTickEvent,
  SimulationEndEvent,
  BackgroundClickEvent,
} from "@heroine-graph/core";
import { createHeroineGraph, isSupported } from "@heroine-graph/core";

/**
 * Props for the HeroineGraph component
 */
export interface HeroineGraphProps {
  /** Graph data to display */
  data?: GraphInput;
  /** Graph configuration */
  config?: Partial<GraphConfig>;
  /** Width of the canvas (default: 100%) */
  width?: string | number;
  /** Height of the canvas (default: 100%) */
  height?: string | number;
  /** CSS class name for the container */
  className?: string;
  /** Enable debug mode */
  debug?: boolean;
}

const props = withDefaults(defineProps<HeroineGraphProps>(), {
  width: "100%",
  height: "100%",
  debug: false,
});

const emit = defineEmits<{
  ready: [graph: HeroineGraphCore];
  error: [error: Error];
  nodeClick: [event: NodeClickEvent];
  nodeDoubleClick: [event: NodeDoubleClickEvent];
  nodeHoverEnter: [event: NodeHoverEnterEvent];
  nodeHoverLeave: [event: NodeHoverLeaveEvent];
  nodeDragStart: [event: NodeDragStartEvent];
  nodeDragMove: [event: NodeDragMoveEvent];
  nodeDragEnd: [event: NodeDragEndEvent];
  edgeClick: [event: EdgeClickEvent];
  edgeHoverEnter: [event: EdgeHoverEnterEvent];
  edgeHoverLeave: [event: EdgeHoverLeaveEvent];
  selectionChange: [event: SelectionChangeEvent];
  viewportChange: [event: ViewportChangeEvent];
  simulationTick: [event: SimulationTickEvent];
  simulationEnd: [event: SimulationEndEvent];
  backgroundClick: [event: BackgroundClickEvent];
}>();

// Template refs
const containerRef = ref<HTMLDivElement | null>(null);
const canvasRef = ref<HTMLCanvasElement | null>(null);

// State
const graph = ref<HeroineGraphCore | null>(null);
const isInitialized = ref(false);
const error = ref<Error | null>(null);

// Expose graph instance to parent
defineExpose({
  /** Get the underlying HeroineGraph instance */
  getGraph: () => graph.value,
  /** Get the canvas element */
  getCanvas: () => canvasRef.value,
});

// Computed styles
const containerStyle = computed<CSSProperties>(() => ({
  width: typeof props.width === "number" ? `${props.width}px` : props.width,
  height: typeof props.height === "number" ? `${props.height}px` : props.height,
  position: "relative",
}));

const errorStyle = computed<CSSProperties>(() => ({
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  width: "100%",
  height: "100%",
  backgroundColor: "#1a1a1a",
  color: "#ff6b6b",
  fontFamily: "system-ui, sans-serif",
  padding: "20px",
  textAlign: "center",
}));

// Event handler registration
function registerEventHandlers(graphInstance: HeroineGraphCore) {
  graphInstance.on("node:click", (e) => emit("nodeClick", e));
  graphInstance.on("node:doubleclick", (e) => emit("nodeDoubleClick", e));
  graphInstance.on("node:hoverenter", (e) => emit("nodeHoverEnter", e));
  graphInstance.on("node:hoverleave", (e) => emit("nodeHoverLeave", e));
  graphInstance.on("node:dragstart", (e) => emit("nodeDragStart", e));
  graphInstance.on("node:dragmove", (e) => emit("nodeDragMove", e));
  graphInstance.on("node:dragend", (e) => emit("nodeDragEnd", e));
  graphInstance.on("edge:click", (e) => emit("edgeClick", e));
  graphInstance.on("edge:hoverenter", (e) => emit("edgeHoverEnter", e));
  graphInstance.on("edge:hoverleave", (e) => emit("edgeHoverLeave", e));
  graphInstance.on("selection:change", (e) => emit("selectionChange", e));
  graphInstance.on("viewport:change", (e) => emit("viewportChange", e));
  graphInstance.on("simulation:tick", (e) => emit("simulationTick", e));
  graphInstance.on("simulation:end", (e) => emit("simulationEnd", e));
  graphInstance.on("background:click", (e) => emit("backgroundClick", e));
}

// Initialize graph
onMounted(async () => {
  const canvas = canvasRef.value;
  if (!canvas) return;

  try {
    // Check WebGPU support
    if (!isSupported()) {
      throw new Error(
        "WebGPU is not supported in this browser. Please use a browser with WebGPU support."
      );
    }

    // Create graph instance
    const graphInstance = await createHeroineGraph({
      canvas,
      config: props.config,
      debug: props.debug,
    });

    graph.value = graphInstance;
    isInitialized.value = true;

    // Register event handlers
    registerEventHandlers(graphInstance);

    // Emit ready event
    emit("ready", graphInstance);

    // Load initial data if provided
    if (props.data) {
      await graphInstance.load(props.data);
    }
  } catch (err) {
    const e = err instanceof Error ? err : new Error(String(err));
    error.value = e;
    emit("error", e);
  }
});

// Cleanup on unmount
onUnmounted(() => {
  if (graph.value) {
    graph.value.dispose();
    graph.value = null;
  }
});

// Watch for data changes
watch(
  () => props.data,
  async (newData) => {
    if (!graph.value || !isInitialized.value || !newData) return;

    try {
      await graph.value.load(newData);
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      error.value = e;
      emit("error", e);
    }
  }
);

// Handle resize
let resizeObserver: ResizeObserver | null = null;

onMounted(() => {
  const container = containerRef.value;
  if (!container) return;

  resizeObserver = new ResizeObserver(() => {
    if (graph.value) {
      graph.value.resize();
    }
  });
  resizeObserver.observe(container);
});

onUnmounted(() => {
  if (resizeObserver) {
    resizeObserver.disconnect();
    resizeObserver = null;
  }
});
</script>

// packages/svelte/src/HeroineGraph.svelte
<!--
  HeroineGraph Svelte Component

  A Svelte wrapper for the Heroine Graph visualization library.
  Handles WebGPU initialization, lifecycle management, and event forwarding.

  @module
-->
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from "svelte";
  import type {
    GraphConfig,
    GraphInput,
    HeroineGraph as HeroineGraphCore,
    NodeClickEvent,
    NodeDoubleClickEvent,
    NodeDragEndEvent,
    NodeDragMoveEvent,
    NodeDragStartEvent,
    NodeHoverEnterEvent,
    NodeHoverLeaveEvent,
    EdgeClickEvent,
    EdgeHoverEnterEvent,
    EdgeHoverLeaveEvent,
    SelectionChangeEvent,
    ViewportChangeEvent,
    SimulationTickEvent,
    SimulationEndEvent,
    BackgroundClickEvent,
  } from "@heroine-graph/core";
  import { createHeroineGraph, isSupported } from "@heroine-graph/core";

  /**
   * Props
   */
  interface Props {
    /** Graph data to display */
    data?: GraphInput;
    /** Graph configuration */
    config?: Partial<GraphConfig>;
    /** Width of the canvas (default: 100%) */
    width?: string | number;
    /** Height of the canvas (default: 100%) */
    height?: string | number;
    /** CSS class name for the container */
    class?: string;
    /** Enable debug mode */
    debug?: boolean;
  }

  let {
    data = undefined,
    config = undefined,
    width = "100%",
    height = "100%",
    class: className = "",
    debug = false,
  }: Props = $props();

  // Event dispatcher
  const dispatch = createEventDispatcher<{
    ready: HeroineGraphCore;
    error: Error;
    nodeClick: NodeClickEvent;
    nodeDoubleClick: NodeDoubleClickEvent;
    nodeHoverEnter: NodeHoverEnterEvent;
    nodeHoverLeave: NodeHoverLeaveEvent;
    nodeDragStart: NodeDragStartEvent;
    nodeDragMove: NodeDragMoveEvent;
    nodeDragEnd: NodeDragEndEvent;
    edgeClick: EdgeClickEvent;
    edgeHoverEnter: EdgeHoverEnterEvent;
    edgeHoverLeave: EdgeHoverLeaveEvent;
    selectionChange: SelectionChangeEvent;
    viewportChange: ViewportChangeEvent;
    simulationTick: SimulationTickEvent;
    simulationEnd: SimulationEndEvent;
    backgroundClick: BackgroundClickEvent;
  }>();

  // State
  let containerEl: HTMLDivElement;
  let canvasEl: HTMLCanvasElement;
  let graph = $state<HeroineGraphCore | null>(null);
  let isInitialized = $state(false);
  let error = $state<Error | null>(null);

  // Computed styles
  const containerStyle = $derived(
    `width: ${typeof width === "number" ? `${width}px` : width}; ` +
    `height: ${typeof height === "number" ? `${height}px` : height}; ` +
    `position: relative;`
  );

  // Expose graph instance
  export function getGraph(): HeroineGraphCore | null {
    return graph;
  }

  export function getCanvas(): HTMLCanvasElement | null {
    return canvasEl;
  }

  // Event handler registration
  function registerEventHandlers(g: HeroineGraphCore) {
    g.on("node:click", (e) => dispatch("nodeClick", e));
    g.on("node:doubleclick", (e) => dispatch("nodeDoubleClick", e));
    g.on("node:hoverenter", (e) => dispatch("nodeHoverEnter", e));
    g.on("node:hoverleave", (e) => dispatch("nodeHoverLeave", e));
    g.on("node:dragstart", (e) => dispatch("nodeDragStart", e));
    g.on("node:dragmove", (e) => dispatch("nodeDragMove", e));
    g.on("node:dragend", (e) => dispatch("nodeDragEnd", e));
    g.on("edge:click", (e) => dispatch("edgeClick", e));
    g.on("edge:hoverenter", (e) => dispatch("edgeHoverEnter", e));
    g.on("edge:hoverleave", (e) => dispatch("edgeHoverLeave", e));
    g.on("selection:change", (e) => dispatch("selectionChange", e));
    g.on("viewport:change", (e) => dispatch("viewportChange", e));
    g.on("simulation:tick", (e) => dispatch("simulationTick", e));
    g.on("simulation:end", (e) => dispatch("simulationEnd", e));
    g.on("background:click", (e) => dispatch("backgroundClick", e));
  }

  // ResizeObserver
  let resizeObserver: ResizeObserver | null = null;

  onMount(async () => {
    if (!canvasEl) return;

    try {
      // Check WebGPU support
      if (!isSupported()) {
        throw new Error(
          "WebGPU is not supported in this browser. Please use a browser with WebGPU support."
        );
      }

      // Create graph instance
      const graphInstance = await createHeroineGraph({
        canvas: canvasEl,
        config,
        debug,
      });

      graph = graphInstance;
      isInitialized = true;

      // Register event handlers
      registerEventHandlers(graphInstance);

      // Emit ready event
      dispatch("ready", graphInstance);

      // Load initial data if provided
      if (data) {
        await graphInstance.load(data);
      }

      // Setup resize observer
      resizeObserver = new ResizeObserver(() => {
        if (graph) {
          graph.resize();
        }
      });
      resizeObserver.observe(containerEl);
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      error = e;
      dispatch("error", e);
    }
  });

  onDestroy(() => {
    if (resizeObserver) {
      resizeObserver.disconnect();
      resizeObserver = null;
    }
    if (graph) {
      graph.dispose();
      graph = null;
    }
  });

  // Watch for data changes using $effect
  $effect(() => {
    if (!graph || !isInitialized || !data) return;

    graph.load(data).catch((err) => {
      const e = err instanceof Error ? err : new Error(String(err));
      error = e;
      dispatch("error", e);
    });
  });
</script>

<div bind:this={containerEl} class={className} style={containerStyle}>
  {#if error}
    <div
      style="
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        height: 100%;
        background-color: #1a1a1a;
        color: #ff6b6b;
        font-family: system-ui, sans-serif;
        padding: 20px;
        text-align: center;
      "
    >
      <div>
        <div style="font-size: 1.2em; margin-bottom: 8px;">
          Failed to initialize graph
        </div>
        <div style="opacity: 0.8; font-size: 0.9em;">{error.message}</div>
      </div>
    </div>
  {:else}
    <canvas
      bind:this={canvasEl}
      style="width: 100%; height: 100%; display: block;"
    />
  {/if}
</div>
